on: push
name: lint

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout project
              uses: actions/checkout@v2
              with:
                  clean: false

            - name: Use Node.js 18
              uses: actions/setup-node@v1
              with:
                  node-version: 18.x

            - name: Install deps
              run: yarn
              
            - name: Install custom packages
              run: yarn add react

            - name: Run ESLint
              run: yarn lint
              env:
                  CI: true
